name: quiz
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  slang: ^4.1.0
  slang_flutter: ^4.1.0
  turkmen_localization_support: ^0.0.9

  # Navigation
  auto_route: ^9.3.0+1

  # State Management
  flutter_mobx: ^2.3.0
  mobx: ^2.5.0

  # Dependency Injection
  injectable: ^2.5.0
  get_it: ^8.0.3

  # Utility
  flutter_dotenv: ^5.2.1

  # Data
  equatable: ^2.0.7
  collection: ^1.19.0
  parse_server_sdk_flutter: ^9.0.0
  shared_preferences: ^2.2.3

  # UI components
  cupertino_icons: ^1.0.8
  dotted_border: ^2.1.0
  
  # Internal Packages
  aks_internal:
    git:
      url: https://github.com/Litesoulo/aks_internal.git
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.13
  slang_build_runner: ^4.4.2
  flutter_gen_runner: ^5.9.0
  mobx_codegen: ^2.7.0
  injectable_generator: ^2.6.2
  auto_route_generator: ^9.0.0

dependency_overrides:
  web: ^1.0.0
  sembast_web: ^2.4.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    # - assets/lottie/
    # - assets/fonts/
    - .env

flutter_gen:
  output: lib/generated/assets/
  line_length: 120

  colors:
    inputs:
      - assets/colors/colors.xml

  # integrations:
  #   flutter_svg: true
  #   lottie: true
